name: dynamic_link_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  share_plus: ^6.3.1

  #Firebase
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0
  firebase_analytics: ^10.0.6
  firebase_in_app_messaging: ^0.7.0+7
  firebase_messaging: ^14.1.4
  firebase_dynamic_links: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
